# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora
java_version=17

# Mod Properties
mod_version=1.0.0
mod_name=Aurora's Canvas
mod_namespace=aurorascanvas
mod_description=A mod all about drawing and self-expression.
fabric_mc_constraints=~1.20 <1.20.2-
support_neoforge=false
neoforge_mc_constraints=[1.20,1.20.1]
modrinth_id=
curseforge_id=

fabric.loom.dropNonIntermediateRootMethods=true
